"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WagmiProvider } from "wagmi";
import { RainbowKitProvider, midnightTheme } from "@rainbow-me/rainbowkit";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { wagmiConfig } from "../utils/wagmi";
import { EquitoProvider } from "../providers/equito-provider";
import { PingPongProvider } from "../providers/ping-pong-provider";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Navbar } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

/* export const metadata: Metadata = { */
/*     title: "Create Next App", */
/*     description: "Generated by create next app", */
/* }; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiProvider config={wagmiConfig}>
          <QueryClientProvider client={queryClient}>
            <RainbowKitProvider
              theme={midnightTheme({
                accentColor: "#6f76f6",
                accentColorForeground: "white",
                borderRadius: "small",
              })}
            >
              <EquitoProvider>
                <PingPongProvider>
                  <Navbar />
                  {children}
                </PingPongProvider>
              </EquitoProvider>
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
